name: trivy_scan
description: Setup Environments and runs trivy_scan

inputs:
  requirements:
    description: requirement file to be used
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python  # Uses python version in .python-version file
      uses: actions/setup-python@v6

    - name: setup virtual environment
      shell: bash
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r ${{ inputs.requirements }}

    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'rootfs'
        scan-ref: '.'
        format: 'table'
        exit-code: 1
        ignore-unfixed: false
        scanners: 'misconfig,vuln,secret'