name: trivy_scan

on:
  workflow_call:
    
jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'rootfs'
          scan-ref: '.'
          format: 'table'
          exit-code: 1
          ignore-unfixed: false
          scanners: 'misconfig,vuln,secret'