name: trivy_scan

on:
  workflow_call:
    
jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python  # Uses python version in .python-version file
        uses: actions/setup-python@v6

      - name: setup virtual environment and run tests
        shell: bash
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements-stg.txt
          
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'rootfs'
          scan-ref: '.'
          format: 'table'
          exit-code: 1
          ignore-unfixed: false
          scanners: 'misconfig,vuln,secret'